alias: "TV power"
initial_state: True
hide_entity: False
trigger:
  - platform: state
    entity_id: input_boolean.tv_power
    state: "on"
  - platform: state
    entity_id: input_boolean.tv_power
    state: "off"
action:
  - service_template: >
      {% if is_state('input_boolean.tv_power', 'on') %}
        hdmi_cec.power_on
      {% elif is_state('input_boolean.tv_power', 'off') %}
        hdmi_cec.standby
      {% endif %}
  - service: input_select.select_option
    data_template:
      entity_id: input_select.avr_input
      option: > 
        {% if is_state('input_boolean.tv_power', 'off') %}
          Standby
        {% endif %}