homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret ravet_latitude
  longitude: !secret ravet_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 548
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Asia/Kolkata
  customize: !include misc/customize.yaml

# Enables the frontend
frontend:

http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret api_password
  cors_allowed_origins:
    - https://google.com
    - https://home-assistant.io
  login_attempts_threshold: 5
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Weather Prediction
sensor:
  platform: yr

# Text to speech
tts:
  platform: google

mqtt:
  broker: 192.168.1.103
  port: 1883
  client_id: home-assistant-1
  username: !secret mqtt_username
  password: !secret mqtt_password

input_boolean: !include misc/input_boolean.yaml
input_select: !include misc/input_select.yaml
input_slider: !include misc/input_slider.yaml
light: !include_dir_list lights/
# switch: !include_dir_list switches/
# group: !include_dir_merge_named groups/