alias: "motion lights lab night"
initial_state: True
hide_entity: False
trigger:
  - platform: state
    entity_id: sensor.aeotec_multisensor_motion_template
    state: "motion detected"
condition:
  - condition: and
    conditions:
      - condition: state
        entity_id: sun.sun
        state: "below_horizon"
      - condition: template
        value_template: "{% if states('input_select.ben_status') != 'Sleeping' and states('input_select.cailin_status') != 'Sleeping' %} true {% else %}false{% endif %}"
      - condition: state
        entity_id: input_boolean.motion_lockout
        state: "off"
  - condition: or
    conditions:
      - condition: state
        entity_id: light.boob_1
        state: "off"
      - condition: state
        entity_id: light.boob_2
        state: "off"
action:
  - service: light.turn_on
    data:
      entity_id:
        - light.boob_1
        - light.boob_2
        - light.megadesk
      brightness: 255
      color_temp: 287
      rgb_color: [255,255,255]
      transition: 2