alias: Media Playing Night
initial_state: True
hide_entity: True
trigger:
  - platform: state
    entity_id: media_player.living_room
    state: "playing"
  - platform: state
    entity_id: media_player.kodi
    state: "playing"
action:
  - service: light.turn_off
    data:
      entity_id:
       - light.switch
       - light.sink
      transition: 15
  - service: light.turn_on
    data:
      entity_id:
       - light.wall
      brightness: 125
      color_temp: 287
      rgb_color: [255,255,255]
      transition: 15